server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: customer
          uri: http://localhost:8082
          predicates:
            - Path=, /myPages/**
        - id: deliver
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: store
          uri: http://localhost:8084
          predicates:
            - Path=/foodCookings/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=, /myPages/**
        - id: deliver
          uri: http://deliver:8080
          predicates:
            - Path=/deliveries/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/foodCookings/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
